const ROLE={GK:['goalkeeper'],CB:['defender','aerial','leader'],LB:['fullback','width','defender'],RB:['fullback','width','defender'],LWB:['wingback','width'],RWB:['wingback','width'],CDM:['ball_winner','controller'],CM:['controller','engine'],CAM:['creator','playmaker'],LM:['wide','creator'],RM:['wide','creator'],LW:['wide','dribbler','finisher'],RW:['wide','dribbler','finisher'],CF:['creator','finisher'],ST:['finisher','aerial']};
const NEEDS={'4-4-2':['finisher','wide','engine','defender','fullback','goalkeeper'],'4-3-3':['wide','finisher','controller','ball_winner','fullback','defender','goalkeeper'],'4-2-3-1':['finisher','creator','ball_winner','wide','defender','goalkeeper'],'3-5-2':['wingback','defender','controller','ball_winner','finisher','goalkeeper'],'3-4-3':['wide','finisher','defender','controller','goalkeeper'],'4-1-2-1-2':['finisher','creator','ball_winner','controller','defender','fullback','goalkeeper'],'4-5-1':['finisher','creator','controller','wide','defender','goalkeeper'],'5-3-2':['wingback','defender','finisher','controller','goalkeeper'],'5-2-3':['wingback','wide','finisher','defender','goalkeeper'],'3-4-1-2':['creator','finisher','defender','controller','goalkeeper']};
const SCARCE={RWB:22,LWB:22,RB:18,LB:18,CDM:17,GK:15,CB:12,RM:10,LM:10,RW:9,LW:9,CAM:9,CF:8,ST:8,CM:6};
export function cleanSearch(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9 ]/g,' ').replace(/\s+/g,' ').trim().toLowerCase()}
const init=n=>String(n||'?').split(' ').filter(Boolean).map(x=>x[0]).join('').slice(0,3).toUpperCase()||'?';
function aliases(p){const n=p.name||'',short=p.short||p.shortName||'';const a=new Set([...(p.aliases||[]),short]);if(/cristiano/i.test(n))a.add('CR7');if(/ronaldo/i.test(n)&&!/cristiano/i.test(n))a.add('R9');if(/de bruyne/i.test(n))a.add('KDB');if(/mbapp/i.test(n))a.add('Mbappe');if(/messi/i.test(n))a.add('Leo Messi');return[...a].filter(Boolean)}
function traits(r,pos){const f={finishing:r-10,creativity:r-10,passing:r-10,dribbling:r-10,pace:r-8,defending:r-14,physicality:r-10,aerial:r-12,pressing:r-10,bigGame:r-6,goalkeeper:5};if(pos.includes('GK'))return{...f,goalkeeper:r,defending:r-8,finishing:5};if(pos.some(x=>['ST','CF','LW','RW'].includes(x)))return{...f,finishing:r,dribbling:r-3,pace:r-2,creativity:r-7};if(pos.some(x=>['CM','CAM','LM','RM'].includes(x)))return{...f,passing:r,creativity:r,dribbling:r-5,pressing:r-7};if(pos.some(x=>['CB','LB','RB','LWB','RWB','CDM'].includes(x)))return{...f,defending:r,physicality:r-5,aerial:r-7,finishing:r-30};return f}
export function normalizePlayer(p){const primary=p.primaryPositions||p.pos||['CM'];const rating=Number(p.rating||p.overall||85);const out={id:p.id||cleanSearch(p.name).replaceAll(' ','-'),canonicalId:p.canonicalId||p.id||cleanSearch(p.name).replaceAll(' ','-'),name:p.name||'Unknown Player',short:p.short||p.shortName||p.name||'Player',shortName:p.shortName||p.short||p.name||'Player',flag:((p.country==='ENG'||p.country==='England'||p.flag==='🏴')?'ENG':(p.flag||'')),country:p.country||'',club:p.club||'All-Time XI',rating,photo:p.photo||init(p.short||p.name),primaryPositions:primary,secondaryPositions:p.secondaryPositions||[],emergencyPositions:p.emergencyPositions||[],pos:primary,aliases:aliases(p),traits:{...traits(rating,primary),...(p.traits||{})},roles:[...(p.roles||[]),...primary.flatMap(x=>ROLE[x]||[])]};out.searchText=cleanSearch([out.name,out.short,out.shortName,out.aliases.join(' '),out.country,out.club,out.primaryPositions.join(' '),out.secondaryPositions.join(' ')].join(' '));return out}
export function buildPlayerPool(...groups){const m=new Map();groups.flat().map(normalizePlayer).forEach(p=>{if(!m.has(p.canonicalId))m.set(p.canonicalId,p)});return[...m.values()].sort((a,b)=>b.rating-a.rating)}
export function getPositionFit(player,pos){const p=normalizePlayer(player),a=p.primaryPositions;if(a.includes(pos))return{category:'primary',score:100,multiplier:1,explanation:`${p.short} is natural at ${pos}.`};if(p.secondaryPositions.includes(pos))return{category:'secondary',score:94,multiplier:.94,explanation:`${p.short} can play ${pos}.`};if(p.emergencyPositions.includes(pos))return{category:'emergency',score:80,multiplier:.8,explanation:`${p.short} can cover ${pos}.`};if(pos==='RWB'&&(a.includes('RB')||a.includes('RM')||a.includes('RW')))return{category:'secondary',score:90,multiplier:.9,explanation:`${p.short} can cover RWB.`};if(pos==='LWB'&&(a.includes('LB')||a.includes('LM')||a.includes('LW')))return{category:'secondary',score:90,multiplier:.9,explanation:`${p.short} can cover LWB.`};if(pos==='RM'&&(a.includes('RW')||a.includes('RWB')))return{category:'secondary',score:88,multiplier:.88,explanation:`${p.short} can cover RM.`};if(pos==='LM'&&(a.includes('LW')||a.includes('LWB')))return{category:'secondary',score:88,multiplier:.88,explanation:`${p.short} can cover LM.`};if(pos==='CF'&&(a.includes('ST')||a.includes('CAM')))return{category:'secondary',score:90,multiplier:.9,explanation:`${p.short} can play CF.`};const groups=[['ST','CF','LW','RW','CAM'],['CM','CDM','LM','RM'],['CB','LB','RB','LWB','RWB']];if(groups.some(g=>g.includes(pos)&&a.some(x=>g.includes(x))))return{category:'stretch',score:62,multiplier:.62,explanation:`${p.short} is stretched out of role.`};return{category:'absurd',score:25,multiplier:(pos==='GK'||a.includes('GK'))?.08:.28,explanation:`${p.short} is badly out of position.`}}
export const fits=(p,pos)=>getPositionFit(p,pos).score>=70;
const slotPos=id=>String(id||'').split('-')[0]||'CM';
const entries=team=>Object.entries(team||{}).filter(([,p])=>p).map(([slot,p])=>({slot,pos:slotPos(slot),player:normalizePlayer(p),fit:getPositionFit(p,slotPos(slot))}));
const avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0;
function roleCounts(es){const c={};es.forEach(e=>e.player.roles.forEach(r=>c[r]=(c[r]||0)+1));return c}
export function evaluateTeam(team,formation='4-3-3'){const es=entries(team),roles=roleCounts(es),tr=k=>avg(es.map(e=>e.player.traits[k]||0));const q=avg(es.map(e=>e.player.rating*e.fit.multiplier));const fit=avg(es.map(e=>e.fit.score));const needs=NEEDS[formation]||[];const covered=needs.filter(n=>roles[n]).length;const categories={playerQuality:q,positionFit:fit,tacticalBalance:Math.min(100,(covered/Math.max(1,needs.length))*82+Math.min(18,es.length)),defensiveStructure:avg(es.filter(e=>['GK','CB','LB','RB','LWB','RWB','CDM'].includes(e.pos)).map(e=>e.player.traits.defending||e.player.rating))||q*.7,midfieldControl:(tr('passing')+tr('creativity')+tr('pressing'))/3,chanceCreation:(tr('creativity')+tr('passing')+tr('dribbling'))/3,finishingThreat:tr('finishing'),chemistry:Math.min(100,60+Object.values(roles).filter(v=>v>1).length*4)};const total=categories.playerQuality*.2+categories.positionFit*.15+categories.tacticalBalance*.2+categories.defensiveStructure*.12+categories.midfieldControl*.12+categories.chanceCreation*.1+categories.finishingThreat*.08+categories.chemistry*.03;return{total,categories,entries:es,roleCoverage:roles,strengths:Object.entries(categories).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([k])=>k),weaknesses:Object.entries(categories).sort((a,b)=>a[1]-b[1]).slice(0,3).map(([k])=>k),keyPlayers:es.sort((a,b)=>b.player.rating*b.fit.multiplier-a.player.rating*a.fit.multiplier).slice(0,4).map(e=>e.player.short)}}
function candidateScore(player,slot,cpuTeam,userTeam,{formation,difficulty}){const fit=getPositionFit(player,slot.pos);const before=evaluateTeam(cpuTeam,formation),after=evaluateTeam({...cpuTeam,[slot.id]:player},formation);const need=Math.max(0,after.total-before.total);const names=cleanSearch(Object.values(userTeam||{}).filter(Boolean).map(p=>p.name+' '+p.short).join(' '));let denial=0;if(names.includes('messi')&&names.includes('neymar')&&/su[aá]rez/i.test(player.name))denial=18;if(names.includes('xavi')&&names.includes('iniesta')&&/busquets/i.test(player.name))denial=16;if(difficulty==='EASY')denial=0;if(difficulty==='MEDIUM')denial*=.45;const redundancy=Object.values(cpuTeam||{}).filter(p=>p&&p.primaryPositions?.some(x=>player.primaryPositions.includes(x))).length*2;const noise={EASY:11,MEDIUM:4,HARD:1}[difficulty]??3;return player.rating*.28+fit.score*.24+need*.22+(SCARCE[slot.pos]||8)+denial-redundancy+Math.random()*noise}
export function chooseCpuPick({slot,blocked,players,cpuTeam={},userTeam={},formation='4-3-3',difficulty='MEDIUM'}){return players.map(normalizePlayer).filter(p=>!blocked.has(p.id)&&!blocked.has(p.canonicalId)).map(p=>({p,s:candidateScore(p,slot,cpuTeam,userTeam,{formation,difficulty})})).sort((a,b)=>b.s-a.s)[0]?.p||null}
const noise=seed=>{let x=0;String(seed).split('').forEach(c=>x=(x*31+c.charCodeAt(0))%9973);return(x%1000)/1000};
const label=k=>String(k).replace(/([A-Z])/g,' $1').toLowerCase();
const byRole=(es,rs)=>es.filter(e=>rs.some(r=>e.player.roles.includes(r))).sort((a,b)=>b.player.rating-a.player.rating)[0]||es.sort((a,b)=>b.player.rating-a.player.rating)[0];
function scoreFor(gap,w){const a=Math.abs(gap);if(a<2)return w==='YOU'?{you:2,cpu:1}:{you:1,cpu:2};if(a<6)return w==='YOU'?{you:3,cpu:2}:{you:2,cpu:3};if(a<11)return w==='YOU'?{you:3,cpu:1}:{you:1,cpu:3};return w==='YOU'?{you:4,cpu:1}:{you:1,cpu:4}}
function matchEvents({winner,score,userEval,cpuEval,teamName}){const we=winner==='YOU'?userEval:cpuEval,le=winner==='YOU'?cpuEval:userEval,wn=winner==='YOU'?teamName:'CPU',ln=winner==='YOU'?'CPU':teamName;const fin=byRole(we.entries,['finisher','wide']),cre=byRole(we.entries,['creator','playmaker','controller']),def=byRole(we.entries,['defender','leader','aerial']),opp=byRole(le.entries,['finisher','wide']);const ev=[['09\'',`${ln} start with pressure, but ${def?.player.short||'the defence'} reads the danger and slows the attack.`],['23\'',`Goal ${wn} — ${cre?.player.short||'the creator'} breaks the line and finds ${fin?.player.short||'the finisher'}, who converts the first clear chance.`],['41\'',`${ln} answer through ${opp?.player.short||'their forward'}, forcing a difficult defensive phase.`],['58\'',`${wn} take control of midfield and force the match into their rhythm.`],['72\'',`Goal ${wn} — the tactical edge becomes another chance, finished by ${fin?.player.short||'the main forward'}.`],['84\'',`${ln} push late, but ${def?.player.short||'the defensive leader'} protects the box when it matters.`]];if(score[winner==='YOU'?'cpu':'you']>0)ev.splice(4,0,['67\'',`Goal ${ln} — ${opp?.player.short||'the striker'} punishes a loose moment and keeps the match alive.`]);return ev}
export function decideMatch({userTeam,cpuTeam,formation='4-3-3',teamName='YOU'}){const userEval=evaluateTeam(userTeam,formation),cpuEval=evaluateTeam(cpuTeam,formation);const raw=userEval.total-cpuEval.total;const finalGap=raw+(noise(Object.values(userTeam).map(p=>p?.id).join('|'))-.5)*(Math.abs(raw)<5?4:1.5);const winner=finalGap>=0?'YOU':'CPU';const score=scoreFor(finalGap,winner);const minutes=matchEvents({winner,score,userEval,cpuEval,teamName});const win=winner==='YOU'?userEval:cpuEval,lose=winner==='YOU'?cpuEval:userEval;const strength=label(win.strengths[0]||'balance'),weak=label(lose.weaknesses[0]||'structure');return{winner,score,minutes,explanation:`${winner==='YOU'?teamName:'CPU'} win because their ${strength} carried the match and punished the opponent's weaker ${weak}. The referee gives the edge to the side with the better mix of position fit, tactical balance, and decisive player impact.`,analysis:{userEval,cpuEval,confidence:Math.min(.95,.52+Math.abs(finalGap)/25),fairnessNote:`Decision based on tactical score ${userEval.total.toFixed(1)} vs ${cpuEval.total.toFixed(1)} before football variance.`}}}
export function searchAvailablePlayers({players,query,slot,used,banned}){const q=cleanSearch(query);return players.map(normalizePlayer).filter(p=>!used.has(p.id)&&!used.has(p.canonicalId)&&!banned.includes(p.id)&&!banned.includes(p.canonicalId)&&getPositionFit(p,slot?.pos).score>=50).filter(p=>!q||p.searchText.includes(q)).map(p=>({p,fit:getPositionFit(p,slot?.pos)})).sort((a,b)=>b.fit.score-a.fit.score||b.p.rating-a.p.rating).map(x=>x.p)}
