const ROLE_MAP={GK:['goalkeeper'],CB:['defender','aerial_defender','defensive_leader'],LB:['fullback','width','defender'],RB:['fullback','width','defender'],LWB:['wingback','width','runner'],RWB:['wingback','width','runner'],CDM:['ball_winner','controller','defensive_midfielder'],CM:['controller','box_to_box','progressor'],CAM:['creator','playmaker'],LM:['wide_threat','creator'],RM:['wide_threat','creator'],LW:['wide_threat','dribbler','finisher'],RW:['wide_threat','dribbler','finisher'],CF:['creator','finisher'],ST:['finisher','aerial_threat']};
const SCARCITY={RWB:22,LWB:22,RB:18,LB:18,CDM:17,GK:15,CB:12,RW:9,LW:9,CAM:9,ST:8,CM:6,LM:10,RM:10,CF:10};
const FORMATION_NEEDS={
 '4-3-3':['wide_threat','finisher','controller','ball_winner','fullback','defender','goalkeeper'],
 '4-2-3-1':['finisher','creator','ball_winner','controller','wide_threat','defender','goalkeeper'],
 '3-5-2':['wingback','defender','controller','ball_winner','finisher','runner','goalkeeper'],
 '3-4-3':['wide_threat','finisher','defender','runner','controller','goalkeeper'],
 '4-4-2':['finisher','wide_threat','box_to_box','defender','fullback','goalkeeper'],
 '4-1-2-1-2':['finisher','creator','ball_winner','controller','defender','fullback','goalkeeper'],
 '4-5-1':['finisher','creator','controller','wide_threat','defender','goalkeeper'],
 '5-3-2':['wingback','defender','finisher','controller','goalkeeper'],
 '5-2-3':['wingback','wide_threat','finisher','defender','runner','goalkeeper'],
 '3-4-1-2':['creator','finisher','runner','defender','controller','goalkeeper']
};
export function cleanSearch(s=''){return String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9 ]/g,' ').replace(/\s+/g,' ').trim().toLowerCase()}
function initials(name='?'){return String(name).split(' ').filter(Boolean).map(x=>x[0]).join('').slice(0,3).toUpperCase()||'?'}
function aliasesFor(p){const n=p.name||'';const short=p.short||p.shortName||'';const aliases=new Set([...(p.aliases||[]),short]);if(/cristiano/i.test(n))aliases.add('CR7');if(/ronaldo/i.test(n)&&!/cristiano/i.test(n))aliases.add('R9');if(/de bruyne/i.test(n))aliases.add('KDB');if(/mbapp/i.test(n))aliases.add('Mbappe');if(/messi/i.test(n))aliases.add('Leo');return [...aliases].filter(Boolean)}
function deriveTraits(r=85,pos=[]){const has=x=>pos.includes(x);const f={finishing:r-8,creativity:r-8,passing:r-8,dribbling:r-8,pace:r-8,defending:r-12,physicality:r-10,aerial:r-12,pressing:r-12,leadership:r-10,bigGame:r-7,consistency:r-6,goalkeeper:5};if(has('GK'))return {...f,goalkeeper:r,defending:r-8,passing:r-18,finishing:5,creativity:10,dribbling:10};if(pos.some(x=>['ST','CF','LW','RW'].includes(x)))return {...f,finishing:r,creativity:r-6,dribbling:r-3,pace:r-2,bigGame:r-3};if(pos.some(x=>['CAM','CM','LM','RM'].includes(x)))return {...f,passing:r,creativity:r,dribbling:r-4,pressing:r-8,defending:r-12};if(pos.some(x=>['CDM','CB','LB','RB','LWB','RWB'].includes(x)))return {...f,defending:r,physicality:r-5,aerial:r-7,passing:r-12,finishing:r-28};return f}
export function normalizePlayer(p){const primary=p.primaryPositions||p.pos||['CM'];const secondary=p.secondaryPositions||[];const emergency=p.emergencyPositions||[];const flag=((p.country==='ENG'||p.country==='England'||p.flag==='🏴')?'ENG':(p.flag||''));const out={id:p.id||cleanSearch(p.name).replaceAll(' ','-'),canonicalId:p.canonicalId||p.id||cleanSearch(p.name).replaceAll(' ','-'),name:p.name||'Unknown Player',short:p.short||p.shortName||p.name||'Player',shortName:p.shortName||p.short||p.name||'Player',flag,country:p.country||'',club:p.club||'All-Time XI',peakEra:p.peakEra||'',rating:Number(p.rating||p.overall||85),primaryPositions:primary,secondaryPositions:secondary,emergencyPositions:emergency,pos:primary,photo:p.photo||initials(p.short||p.name),traits:{...deriveTraits(Number(p.rating||p.overall||85),primary),...(p.traits||{})},roles:[...(p.roles||[]),...primary.flatMap(x=>ROLE_MAP[x]||[])],tacticalTags:p.tacticalTags||[],chemistryTags:p.chemistryTags||[],aliases:aliasesFor(p),confidence:p.confidence??0.75};out.searchText=cleanSearch([out.name,out.short,out.shortName,out.aliases.join(' '),out.country,out.club,out.primaryPositions.join(' '),out.secondaryPositions.join(' ')].join(' '));return out}
export function buildPlayerPool(...groups){const map=new Map();groups.flat().map(normalizePlayer).forEach(p=>{if(p.id&&!map.has(p.canonicalId))map.set(p.canonicalId,p)});return [...map.values()].sort((a,b)=>b.rating-a.rating)}
export function getPositionFit(player,pos){const p=normalizePlayer(player);if(p.primaryPositions.includes(pos))return{category:'primary',multiplier:1,score:100,explanation:`${p.short} is natural at ${pos}.`};if(p.secondaryPositions.includes(pos))return{category:'secondary',multiplier:.94,score:94,explanation:`${p.short} can play ${pos} at a high level.`};if(p.emergencyPositions.includes(pos))return{category:'emergency',multiplier:.8,score:80,explanation:`${p.short} can cover ${pos}, but it is not ideal.`};const a=p.primaryPositions;if(pos==='RWB'&&(a.includes('RB')||a.includes('RM')||a.includes('RW')))return{category:'secondary',multiplier:.9,score:90,explanation:`${p.short} has the profile to cover RWB.`};if(pos==='LWB'&&(a.includes('LB')||a.includes('LM')||a.includes('LW')))return{category:'secondary',multiplier:.9,score:90,explanation:`${p.short} has the profile to cover LWB.`};if(pos==='RM'&&(a.includes('RW')||a.includes('RWB')))return{category:'secondary',multiplier:.88,score:88,explanation:`${p.short} can cover the right side.`};if(pos==='LM'&&(a.includes('LW')||a.includes('LWB')))return{category:'secondary',multiplier:.88,score:88,explanation:`${p.short} can cover the left side.`};if(pos==='CF'&&(a.includes('ST')||a.includes('CAM')))return{category:'secondary',multiplier:.9,score:90,explanation:`${p.short} can operate centrally in attack.`};const attack=['ST','CF','LW','RW','CAM'];const mid=['CM','CDM','LM','RM'];const def=['CB','LB','RB','LWB','RWB'];const same=(g)=>g.includes(pos)&&a.some(x=>g.includes(x));if(same(attack)||same(mid)||same(def))return{category:'stretch',multiplier:.62,score:62,explanation:`${p.short} is being stretched away from his best role.`};return{category:'absurd',multiplier:pos==='GK'||a.includes('GK')?.08:.28,score:28,explanation:`${p.short} is badly out of position at ${pos}.`}}
export function fits(player,pos){return getPositionFit(player,pos).score>=70}
function slotPos(id=''){return String(id).split('-')[0]||'CM'}
function teamPlayers(team){return Object.entries(team||{}).filter(([,p])=>p).map(([slot,p])=>({slot,pos:slotPos(slot),player:normalizePlayer(p),fit:getPositionFit(p,slotPos(slot))}))}
function roleCoverage(entries){const counts={};entries.forEach(e=>e.player.roles.forEach(r=>counts[r]=(counts[r]||0)+1));return counts}
function avg(arr){return arr.length?arr.reduce((a,b)=>a+b,0)/arr.length:0}
export function evaluateTeam(team,formation='4-3-3',opponent={}){const entries=teamPlayers(team);const roles=roleCoverage(entries);const q=avg(entries.map(e=>e.player.rating*e.fit.multiplier));const fit=avg(entries.map(e=>e.fit.score));const traits=k=>avg(entries.map(e=>e.player.traits[k]||0));const defense=avg(entries.filter(e=>['GK','CB','LB','RB','LWB','RWB','CDM'].includes(e.pos)).map(e=>e.player.traits.defending||e.player.rating));const midfield=(traits('passing')+traits('creativity')+traits('pressing'))/3;const creation=(traits('creativity')+traits('passing')+traits('dribbling'))/3;const finishing=traits('finishing');const keeper=avg(entries.filter(e=>e.pos==='GK').map(e=>e.player.traits.goalkeeper||e.player.rating));const needs=FORMATION_NEEDS[formation]||[];const covered=needs.filter(n=>roles[n]).length;const tacticalBalance=Math.min(100,(covered/Math.max(1,needs.length))*82+Math.min(18,entries.length));const width=(roles.wide_threat||0)+(roles.fullback||0)+(roles.wingback||0);const chemistry=Math.min(100,60+(entries.length?10:0)+Object.values(roles).filter(v=>v>1).length*3);const categories={playerQuality:q,positionFit:fit,tacticalBalance,defensiveStructure:defense||q*.7,midfieldControl:midfield,chanceCreation:creation,finishingThreat:finishing,width:Math.min(100,50+width*10),paceThreat:traits('pace'),pressing:traits('pressing'),goalkeeperSecurity:keeper||50,chemistry};const total=categories.playerQuality*.2+categories.positionFit*.15+categories.tacticalBalance*.2+categories.defensiveStructure*.12+categories.midfieldControl*.12+categories.chanceCreation*.1+categories.finishingThreat*.08+categories.chemistry*.03;const strengths=Object.entries(categories).sort((a,b)=>b[1]-a[1]).slice(0,3).map(([k])=>k);const weaknesses=Object.entries(categories).sort((a,b)=>a[1]-b[1]).slice(0,3).map(([k])=>k);const keyPlayers=entries.sort((a,b)=>b.player.rating*a.fit.multiplier-a.player.rating*b.fit.multiplier).slice(0,4).map(e=>e.player.short);return{total,categories,strengths,weaknesses,keyPlayers,roleCoverage:roles,entries}}
function candidateScore(player,slot,cpuTeam,userTeam,draftState){const fit=getPositionFit(player,slot.pos);const rating=player.rating;const tempTeam={...cpuTeam,[slot.id]:player};const before=evaluateTeam(cpuTeam,draftState.formation);const after=evaluateTeam(tempTeam,draftState.formation);const formationNeed=Math.max(0,after.total-before.total);const scarcity=SCARCITY[slot.pos]||8;const userNames=Object.values(userTeam||{}).filter(Boolean).map(p=>cleanSearch(p.name+' '+p.short)).join(' ');let denial=0;if(/messi/.test(userNames)&&/neymar/.test(userNames)&&/su[aá]rez/i.test(player.name))denial=18;if(/xavi/.test(userNames)&&/iniesta/.test(userNames)&&/busquets/i.test(player.name))denial=16;if((draftState.difficulty||'MEDIUM')==='EASY')denial=0;if((draftState.difficulty||'MEDIUM')==='MEDIUM')denial*=.45;const redundancy=Object.values(cpuTeam||{}).filter(p=>p&&p.primaryPositions?.some(x=>player.primaryPositions.includes(x))).length*2.2;const noise={EASY:10,MEDIUM:4,HARD:1}[draftState.difficulty]??3;const total=rating*.28+fit.score*.24+formationNeed*.22+scarcity+denial-redundancy+Math.random()*noise;return{totalScore:total,breakdown:{rating,positionFit:fit.score,formationNeed,scarcity,denial,redundancyPenalty:redundancy},explanation:`${player.short}: ${fit.explanation}`}}
export function chooseCpuPick({slot,blocked,players,cpuTeam={},userTeam={},formation='4-3-3',difficulty='MEDIUM'}){const legal=players.map(normalizePlayer).filter(p=>!blocked.has(p.id)&&!blocked.has(p.canonicalId));const scored=legal.map(p=>({player:p,...candidateScore(p,slot,cpuTeam,userTeam,{formation,difficulty})})).sort((a,b)=>b.totalScore-a.totalScore);return scored[0]?.player||null}
function seededNoise(seed){let x=0;String(seed).split('').forEach(c=>x=(x*31+c.charCodeAt(0))%9973);return (x%1000)/1000}
function scorelineFor(gap,winner){const abs=Math.abs(gap);if(abs<2)return winner==='YOU'?{you:2,cpu:1}:{you:1,cpu:2};if(abs<6)return winner==='YOU'?{you:3,cpu:2}:{you:2,cpu:3};if(abs<11)return winner==='YOU'?{you:3,cpu:1}:{you:1,cpu:3};return winner==='YOU'?{you:4,cpu:1}:{you:1,cpu:4}}
function bestByRole(entries,roles){return entries.filter(e=>roles.some(r=>e.player.roles.includes(r))).sort((a,b)=>b.player.rating-a.player.rating)[0]||entries.sort((a,b)=>b.player.rating-a.player.rating)[0]}
export function simulateMatch({winner,score,userEval,cpuEval,teamName='YOU'}){const winEval=winner==='YOU'?userEval:cpuEval;const loseEval=winner==='YOU'?cpuEval:userEval;const winName=winner==='YOU'?teamName:'CPU';const loseName=winner==='YOU'?'CPU':teamName;const wp=winEval.entries;const lp=loseEval.entries;const fin=bestByRole(wp,['finisher','wide_threat']);const creator=bestByRole(wp,['creator','playmaker','controller']);const def=bestByRole(wp,['defender','defensive_leader','aerial_defender']);const lFin=bestByRole(lp,['finisher','wide_threat']);const events=[['09\'',`${loseName} start brightly, but ${def?.player.short||'the defence'} reads the danger and slows the first attack.`],['23\'',`Goal ${winName} — ${creator?.player.short||'the creator'} breaks the line and finds ${fin?.player.short||'the finisher'}, who converts the first clear chance.`],['41\'',`${loseName} answer with pressure through ${lFin?.player.short||'their forward'}, forcing a difficult defensive phase.`],['58\'',`${winName} take control of midfield and begin forcing the match into their preferred rhythm.`],['72\'',`Goal ${winName} — the tactical edge turns into another chance, finished by ${fin?.player.short||'the main forward'}.`],['84\'',`${loseName} push late, but ${def?.player.short||'the defensive leader'} protects the box when it matters.`]];if(score[winner==='YOU'?'cpu':'you']>0)events.splice(4,0,['67\'',`Goal ${loseName} — ${lFin?.player.short||'the striker'} punishes a loose moment and keeps the match alive.`]);return events}
export function decideMatch({userTeam,cpuTeam,formation='4-3-3',teamName='YOU'}){const userEval=evaluateTeam(userTeam,formation,cpuTeam);const cpuEval=evaluateTeam(cpuTeam,formation,userTeam);const rawGap=userEval.total-cpuEval.total;const variance=(seededNoise(Object.values(userTeam).map(p=>p?.id).join('|'))-.5)*(Math.abs(rawGap)<5?4:1.5);const finalGap=rawGap+variance;const winner=finalGap>=0?'YOU':'CPU';const score=scorelineFor(finalGap,winner);const minutes=simulateMatch({winner,score,userEval,cpuEval,teamName});const winnerEval=winner==='YOU'?userEval:cpuEval;const loserEval=winner==='YOU'?cpuEval:userEval;const mainStrength=winnerEval.strengths[0]?.replace(/([A-Z])/g,' $1').toLowerCase()||'balance';const punished=loserEval.weaknesses[0]?.replace(/([A-Z])/g,' $1').toLowerCase()||'structure';const explanation=`${winner==='YOU'?teamName:'CPU'} win because their ${mainStrength} carried the match and punished the opponent's weaker ${punished}. The referee gives the edge to the side with the better mix of position fit, tactical balance, and decisive player impact.`;return{winner,score,minutes,explanation,analysis:{userEval,cpuEval,confidence:Math.min(.95,.52+Math.abs(finalGap)/25),decisiveFactors:[mainStrength,punished],fairnessNote:`Decision based on tactical score ${userEval.total.toFixed(1)} vs ${cpuEval.total.toFixed(1)} before football variance.`}}}
export function searchAvailablePlayers({players,query,slot,used,banned}){const cq=cleanSearch(query);return players.map(normalizePlayer).filter(p=>!used.has(p.id)&&!used.has(p.canonicalId)&&!banned.includes(p.id)&&!banned.includes(p.canonicalId)&&getPositionFit(p,slot?.pos).score>=50).filter(p=>!cq||p.searchText.includes(cq)).map(p=>({p,fit:getPositionFit(p,slot?.pos)})).sort((a,b)=>b.fit.score-a.fit.score||b.p.rating-a.p.rating).map(x=>x.p)}
